# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build html documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Also build HTMLZip, PDF and ePub
# TODO: do we need all these as well?
formats:
  - pdf

# Install the pinned dependencies for the documentation building process.
python:
  install:
    - requirements: doc/requirements.txt

# This is not currently needed, it is included so documentation will not break, if functionality is moved into
# submodules.
submodules:
  include: all
  recursive: true
