#!/bin/sh
# see: dh_installdeb(1)

set -e

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql
fi

unset_sites () {
    if [ ! "upgrade" = "$1" ]; then
        rm -f /etc/apache2/sites-enabled/privacyidea.conf
    fi
}

unset_sites $1


#DEBHELPER#
exit 0
