<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "privacyidea"
 *
 * Auto generated by Extension Builder 2015-04-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'privacyidea',
	'description' => 'Two factor authentication for TYPO3 frontend and backend authenticating against your own privacyIDEA server.
privacyIDEA supports many different type of authentication devices like OTP token, display cards, Yubikey, SMS, Email...',
	'category' => 'services',
	'author' => 'Cornelius Kölbel',
	'author_email' => 'cornelius.koelbel@netknights.it',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);