# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61service.proto\";\n\x10SetOptionRequest\x12\x12\n\noptionName\x18\x01 \x01(\t\x12\x13\n\x0boptionValue\x18\x02 \x01(\t\" \n\x0eSetOptionReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\"C\n\x0fSubmitCRRequest\x12\n\n\x02\x63r\x18\x01 \x01(\t\x12\x14\n\x0ctemplateName\x18\x02 \x01(\t\x12\x0e\n\x06\x63\x61Name\x18\x03 \x01(\t\"g\n\rSubmitCRReply\x12\x13\n\x0b\x64isposition\x18\x01 \x01(\x05\x12\x1a\n\x12\x64ispositionMessage\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\x05\x12\x12\n\nlastStatus\x18\x04 \x01(\x03\"\x0f\n\rGetCAsRequest\"\x1d\n\x0bGetCAsReply\x12\x0e\n\x06\x63\x61Name\x18\x01 \x03(\t\"3\n\x15GetCertificateRequest\x12\x0e\n\x06\x63\x61Name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"#\n\x13GetCertificateReply\x12\x0c\n\x04\x63\x65rt\x18\x01 \x01(\t\"%\n\x13GetTemplatesRequest\x12\x0e\n\x06\x63\x61Name\x18\x01 \x01(\t\")\n\x11GetTemplatesReply\x12\x14\n\x0ctemplateName\x18\x01 \x03(\t\"a\n\x12GetCRStatusRequest\x12\x0e\n\x06\x63\x61Name\x18\x01 \x01(\t\x12\x17\n\rcertRequestId\x18\x02 \x01(\x05H\x00\x12\x14\n\ncertSerial\x18\x03 \x01(\tH\x00\x42\x0c\n\nIDorSerial\"q\n\x10GetCRStatusReply\x12\x13\n\x0b\x64isposition\x18\x01 \x01(\x05\x12\x1a\n\x12\x64ispositionMessage\x18\x02 \x01(\t\x12\x12\n\nlastStatus\x18\x03 \x01(\x03\x12\x18\n\x10\x65rrorMessageText\x18\x04 \x01(\t2\xc3\x02\n\tCAService\x12,\n\x08SubmitCR\x12\x10.SubmitCRRequest\x1a\x0e.SubmitCRReply\x12&\n\x06GetCAs\x12\x0e.GetCAsRequest\x1a\x0c.GetCAsReply\x12>\n\x0eGetCertificate\x12\x16.GetCertificateRequest\x1a\x14.GetCertificateReply\x12\x38\n\x0cGetTemplates\x12\x14.GetTemplatesRequest\x1a\x12.GetTemplatesReply\x12\x35\n\x0bGetCRStatus\x12\x13.GetCRStatusRequest\x1a\x11.GetCRStatusReply\x12/\n\tSetOption\x12\x11.SetOptionRequest\x1a\x0f.SetOptionReplyB\x07\xaa\x02\x04Grpcb\x06proto3')



_SETOPTIONREQUEST = DESCRIPTOR.message_types_by_name['SetOptionRequest']
_SETOPTIONREPLY = DESCRIPTOR.message_types_by_name['SetOptionReply']
_SUBMITCRREQUEST = DESCRIPTOR.message_types_by_name['SubmitCRRequest']
_SUBMITCRREPLY = DESCRIPTOR.message_types_by_name['SubmitCRReply']
_GETCASREQUEST = DESCRIPTOR.message_types_by_name['GetCAsRequest']
_GETCASREPLY = DESCRIPTOR.message_types_by_name['GetCAsReply']
_GETCERTIFICATEREQUEST = DESCRIPTOR.message_types_by_name['GetCertificateRequest']
_GETCERTIFICATEREPLY = DESCRIPTOR.message_types_by_name['GetCertificateReply']
_GETTEMPLATESREQUEST = DESCRIPTOR.message_types_by_name['GetTemplatesRequest']
_GETTEMPLATESREPLY = DESCRIPTOR.message_types_by_name['GetTemplatesReply']
_GETCRSTATUSREQUEST = DESCRIPTOR.message_types_by_name['GetCRStatusRequest']
_GETCRSTATUSREPLY = DESCRIPTOR.message_types_by_name['GetCRStatusReply']
SetOptionRequest = _reflection.GeneratedProtocolMessageType('SetOptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETOPTIONREQUEST,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:SetOptionRequest)
  })
_sym_db.RegisterMessage(SetOptionRequest)

SetOptionReply = _reflection.GeneratedProtocolMessageType('SetOptionReply', (_message.Message,), {
  'DESCRIPTOR' : _SETOPTIONREPLY,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:SetOptionReply)
  })
_sym_db.RegisterMessage(SetOptionReply)

SubmitCRRequest = _reflection.GeneratedProtocolMessageType('SubmitCRRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITCRREQUEST,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:SubmitCRRequest)
  })
_sym_db.RegisterMessage(SubmitCRRequest)

SubmitCRReply = _reflection.GeneratedProtocolMessageType('SubmitCRReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITCRREPLY,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:SubmitCRReply)
  })
_sym_db.RegisterMessage(SubmitCRReply)

GetCAsRequest = _reflection.GeneratedProtocolMessageType('GetCAsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCASREQUEST,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetCAsRequest)
  })
_sym_db.RegisterMessage(GetCAsRequest)

GetCAsReply = _reflection.GeneratedProtocolMessageType('GetCAsReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCASREPLY,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetCAsReply)
  })
_sym_db.RegisterMessage(GetCAsReply)

GetCertificateRequest = _reflection.GeneratedProtocolMessageType('GetCertificateRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCERTIFICATEREQUEST,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetCertificateRequest)
  })
_sym_db.RegisterMessage(GetCertificateRequest)

GetCertificateReply = _reflection.GeneratedProtocolMessageType('GetCertificateReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCERTIFICATEREPLY,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetCertificateReply)
  })
_sym_db.RegisterMessage(GetCertificateReply)

GetTemplatesRequest = _reflection.GeneratedProtocolMessageType('GetTemplatesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTEMPLATESREQUEST,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetTemplatesRequest)
  })
_sym_db.RegisterMessage(GetTemplatesRequest)

GetTemplatesReply = _reflection.GeneratedProtocolMessageType('GetTemplatesReply', (_message.Message,), {
  'DESCRIPTOR' : _GETTEMPLATESREPLY,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetTemplatesReply)
  })
_sym_db.RegisterMessage(GetTemplatesReply)

GetCRStatusRequest = _reflection.GeneratedProtocolMessageType('GetCRStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCRSTATUSREQUEST,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetCRStatusRequest)
  })
_sym_db.RegisterMessage(GetCRStatusRequest)

GetCRStatusReply = _reflection.GeneratedProtocolMessageType('GetCRStatusReply', (_message.Message,), {
  'DESCRIPTOR' : _GETCRSTATUSREPLY,
  '__module__' : 'caservice_pb2'
  # @@protoc_insertion_point(class_scope:GetCRStatusReply)
  })
_sym_db.RegisterMessage(GetCRStatusReply)

_CASERVICE = DESCRIPTOR.services_by_name['CAService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\004Grpc'
  _SETOPTIONREQUEST._serialized_start=19
  _SETOPTIONREQUEST._serialized_end=78
  _SETOPTIONREPLY._serialized_start=80
  _SETOPTIONREPLY._serialized_end=112
  _SUBMITCRREQUEST._serialized_start=114
  _SUBMITCRREQUEST._serialized_end=181
  _SUBMITCRREPLY._serialized_start=183
  _SUBMITCRREPLY._serialized_end=286
  _GETCASREQUEST._serialized_start=288
  _GETCASREQUEST._serialized_end=303
  _GETCASREPLY._serialized_start=305
  _GETCASREPLY._serialized_end=334
  _GETCERTIFICATEREQUEST._serialized_start=336
  _GETCERTIFICATEREQUEST._serialized_end=387
  _GETCERTIFICATEREPLY._serialized_start=389
  _GETCERTIFICATEREPLY._serialized_end=424
  _GETTEMPLATESREQUEST._serialized_start=426
  _GETTEMPLATESREQUEST._serialized_end=463
  _GETTEMPLATESREPLY._serialized_start=465
  _GETTEMPLATESREPLY._serialized_end=506
  _GETCRSTATUSREQUEST._serialized_start=508
  _GETCRSTATUSREQUEST._serialized_end=605
  _GETCRSTATUSREPLY._serialized_start=607
  _GETCRSTATUSREPLY._serialized_end=720
  _CASERVICE._serialized_start=723
  _CASERVICE._serialized_end=1046
# @@protoc_insertion_point(module_scope)
