"""v3.10: Add table nodename

Revision ID: e3a64b4ca634
Revises: 5cb310101a1f
Create Date: 2023-11-23 11:41:30.149153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import DatabaseError

# revision identifiers, used by Alembic.
revision = 'e3a64b4ca634'
down_revision = '5cb310101a1f'


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('nodename',
                        sa.Column('id', sa.Unicode(length=36), nullable=False),
                        sa.Column('name', sa.Unicode(length=100), nullable=True),
                        sa.Column('lastseen', sa.DateTime(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index(op.f('ix_nodename_lastseen'), 'nodename', ['lastseen'], unique=False)
        op.create_index(op.f('ix_nodename_name'), 'nodename', ['name'], unique=False)
        # ### end Alembic commands ###
    except DatabaseError as exx:
        print("Could not add column 'priority' to table 'resolverrealm'")
        print(exx)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodename_name'), table_name='nodename')
    op.drop_index(op.f('ix_nodename_lastseen'), table_name='nodename')
    op.drop_table('nodename')
    # ### end Alembic commands ###
