#!/bin/sh
# see: dh_installdeb(1)

set -e

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql
fi

unset_sites () {
	rm -f /etc/nginx/sites-enabled/privacycidea
	rm -f /etc/uwsgi/apps-enabled/privacyidea.xml
}


unset_sites


#DEBHELPER#
exit 0
