"""v3.13: Change the Audit id column type to BigInt

Revision ID: 06b105a4f941
Revises: b637a1eeeeeb
Create Date: 2026-03-04 16:58:10.266368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b105a4f941'
down_revision = 'b637a1eeeeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pidea_audit', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              type_=sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'),
                              existing_nullable=False,
                              autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pidea_audit', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'),
                              type_=sa.INTEGER(),
                              existing_nullable=False,
                              autoincrement=True)

    # ### end Alembic commands ###
