"""empty message

Revision ID: 3dd1673fb275
Revises: 056b6642ff5d
Create Date: 2026-01-16 10:05:30.526133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3dd1673fb275'
down_revision = '056b6642ff5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtpserver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smime', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtpserver', schema=None) as batch_op:
        batch_op.drop_column('smime')
    # ### end Alembic commands ###
