"""v3.12: Increase audit column sizes and change policy action type to text

Revision ID: 41ad6c9ada8b
Revises: 5f40baab76ca
Create Date: 2025-07-17 09:22:35.283486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ad6c9ada8b'
down_revision = '5f40baab76ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pidea_audit', schema=None) as batch_op:
        batch_op.alter_column('action',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.Unicode(length=200),
                              existing_nullable=True)
        batch_op.alter_column('container_serial',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.Unicode(length=40),
                              existing_nullable=True)
        batch_op.alter_column('container_type',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.Unicode(length=100),
                              existing_nullable=True)
        batch_op.alter_column('user',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.Unicode(length=100),
                              existing_nullable=True)
        batch_op.alter_column('realm',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.Unicode(length=255),
                              existing_nullable=True)
        batch_op.alter_column('resolver',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.Unicode(length=255),
                              existing_nullable=True)
        batch_op.alter_column('administrator',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.Unicode(length=100),
                              existing_nullable=True)
        batch_op.alter_column('action_detail',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.Unicode(length=500),
                              existing_nullable=True)
        batch_op.alter_column('info',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.Unicode(length=500),
                              existing_nullable=True)
        batch_op.alter_column('user_agent',
                              existing_type=sa.VARCHAR(length=20),
                              type_=sa.Unicode(length=50),
                              existing_nullable=True)

    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('action',
                              existing_type=sa.VARCHAR(length=2000),
                              type_=sa.Text(),
                              existing_nullable=True)

    with op.batch_alter_table('realm', schema=None) as batch_op:
        batch_op.drop_column('option')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option', sa.VARCHAR(length=40), autoincrement=False, nullable=True))

    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('action',
                              existing_type=sa.Text(),
                              type_=sa.VARCHAR(length=2000),
                              existing_nullable=True)

    with op.batch_alter_table('pidea_audit', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
                              existing_type=sa.Unicode(length=50),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=True)
        batch_op.alter_column('info',
                              existing_type=sa.Unicode(length=500),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=True)
        batch_op.alter_column('action_detail',
                              existing_type=sa.Unicode(length=500),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=True)
        batch_op.alter_column('administrator',
                              existing_type=sa.Unicode(length=100),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=True)
        batch_op.alter_column('resolver',
                              existing_type=sa.Unicode(length=255),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=True)
        batch_op.alter_column('realm',
                              existing_type=sa.Unicode(length=255),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=True)
        batch_op.alter_column('user',
                              existing_type=sa.Unicode(length=100),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=True)
        batch_op.alter_column('container_type',
                              existing_type=sa.Unicode(length=100),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=True)
        batch_op.alter_column('container_serial',
                              existing_type=sa.Unicode(length=40),
                              type_=sa.VARCHAR(length=20),
                              existing_nullable=True)
        batch_op.alter_column('action',
                              existing_type=sa.Unicode(length=200),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=True)

    # ### end Alembic commands ###
