"""v3.12: Add column 'handle_missing_data' to the policycondition table

Revision ID: 5f40baab76ca
Revises: 903a6ed6f6c4
Create Date: 2025-04-04 09:57:56.313709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError, ProgrammingError

# revision identifiers, used by Alembic.
revision = '5f40baab76ca'
down_revision = '903a6ed6f6c4'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('policycondition',
                      sa.Column('handle_missing_data', sa.Unicode(length=255), nullable=True))
    except (OperationalError, ProgrammingError) as exx:
        if "already exists" in str(exx.orig).lower() or "duplicate column name" in str(exx.orig).lower():
            print("Column 'handle_missing_data' already exists.")
        else:
            print("Could not add column 'handle_missing_data' to table 'policycondition'.")
            print(exx)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('policycondition', 'handle_missing_data')
    except (OperationalError, ProgrammingError) as exx:
        msg = str(exx.orig).lower()
        if "no such column" in msg or "does not exist" in msg:
            print("Column 'handle_missing_data' already removed.")
        else:
            print("Could not remove column 'handle_missing_data' from table 'policycondition'.")
            print(exx)

    # ### end Alembic commands ###
