"""v3.14: Add clients table for API-key based client authentication

Revision ID: b7c8d9e0f1a2
Revises: c3d4e5f6a7b8
Create Date: 2026-07-22 00:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.exc import OperationalError, ProgrammingError

# revision identifiers, used by Alembic.
revision = 'b7c8d9e0f1a2'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    try:
        op.create_table(
            'clients',
            # The primary key is a string UUID generated by the application, so
            # no database sequence is required.
            sa.Column('id', sa.Unicode(length=36), nullable=False),
            sa.Column('display_name', sa.Unicode(length=255), nullable=False),
            sa.Column('client_type', sa.Unicode(length=64), nullable=False),
            # Public, non-secret identifier used to look up the client. Only the
            # secret half of the key is hashed into key_hash.
            sa.Column('key_id', sa.Unicode(length=32), nullable=False),
            sa.Column('key_hash', sa.Unicode(length=64), nullable=False),
            sa.Column('status', sa.Unicode(length=16), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('last_used_at', sa.DateTime(), nullable=True),
            sa.Column('config', sa.JSON(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            # Every request looks the client up by key_id, so it must be unique
            # and indexed.
            sa.UniqueConstraint('key_id', name='uq_clients_key_id'),
        )
    except (OperationalError, ProgrammingError) as ex:
        if "already exists" in str(ex.orig).lower():
            print("Table 'clients' already exists.")
        else:
            print("Could not add table 'clients' to database.")
            raise


def downgrade():
    try:
        op.drop_table('clients')
    except (OperationalError, ProgrammingError) as ex:
        msg = str(ex.orig).lower()
        if "no such table" in msg or "unknown table" in msg or "does not exist" in msg:
            print("Table 'clients' already removed.")
        else:
            print("Could not remove table 'clients'.")
            raise
