"""v3.14: Add remembered_devices table for persistent (remember-device) devices

Revision ID: c8d9e0f1a2b3
Revises: b7c8d9e0f1a2
Create Date: 2026-07-22 00:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.exc import OperationalError, ProgrammingError

# revision identifiers, used by Alembic.
revision = 'c8d9e0f1a2b3'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None


def upgrade():
    try:
        op.create_table(
            'remembered_devices',
            # series_id is a random url-safe string generated by the application,
            # so no database sequence is required.
            sa.Column('series_id', sa.Unicode(length=64), nullable=False),
            sa.Column('counter', sa.Integer(), nullable=False),
            sa.Column('client_id', sa.Unicode(length=36), nullable=False),
            # The remembered user is bound by the resolver-stable identity
            # (resolver, user_id, realm_id), not by the login name - mirroring
            # how tokenowner binds a user. user_id is the resolver's immutable id.
            sa.Column('resolver', sa.Unicode(length=120), nullable=False),
            sa.Column('user_id', sa.Unicode(length=320), nullable=False),
            sa.Column('realm_id', sa.Integer(), nullable=False),
            sa.Column('ip_address', sa.Unicode(length=64), nullable=True),
            sa.Column('user_agent', sa.Unicode(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('last_used_at', sa.DateTime(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('series_id'),
            # A device belongs to exactly one client; deleting the client
            # removes its devices.
            sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
            # A device belongs to a realm; deleting the realm removes its devices.
            sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ondelete='CASCADE'),
            # Devices are looked up by (series_id, client_id); the user-identity
            # and realm columns are indexed for revoke-by-user / revoke-by-realm.
            sa.Index('ix_remembered_devices_client_id', 'client_id'),
            sa.Index('ix_remembered_devices_resolver', 'resolver'),
            sa.Index('ix_remembered_devices_user_id', 'user_id'),
            sa.Index('ix_remembered_devices_realm_id', 'realm_id'),
        )
    except (OperationalError, ProgrammingError) as ex:
        if "already exists" in str(ex.orig).lower():
            print("Table 'remembered_devices' already exists.")
        else:
            print("Could not add table 'remembered_devices' to database.")
            raise


def downgrade():
    try:
        op.drop_table('remembered_devices')
    except (OperationalError, ProgrammingError) as ex:
        msg = str(ex.orig).lower()
        if "no such table" in msg or "unknown table" in msg or "does not exist" in msg:
            print("Table 'remembered_devices' already removed.")
        else:
            print("Could not remove table 'remembered_devices'.")
            raise
