.\" Manpage for privacyidea-fetchssh
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-FETCHSSH  1 "11 Oct 2015" "1.0" "privacyidea-fetchssh man page"
.SH NAME
privacyidea-fetchssh \- Fetch the defined ssh public keys from the privacyIDEA server.
.SH SYNOPSIS
privacyidea-fetchssh
.SH DESCRIPTION
This fetches the public SSH keys from the privacyIDEA server. This script is to be used with
the authorized_keys_command in the sshd_config of the OpenSSH server.

.SH INTERNET SOURCES
http://www.privacyidea.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Peter Murr, privacyIDEA <info@privacyidea.org>
