.\" Manpage for privacyidea-create-certificate.
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-CREATE-CERTIFICATE 1 "11 Oct 2015" "1.0" "privacyidea-create-certificate man page"
.SH NAME
privacyidea-create-certificate \- create the webserver certificate.
.SH SYNOPSIS
privacyidea-create-auditkeys \-f <apache config>
.SH DESCRIPTION
This tool creates the private key and the self\-signed certificate for the privacyIDEA webserver.
It reads the privacyidea apache config and thus gets the information, where the certificate and
the key should be located.
.SH COMMON OPTIONS
.PP
\fB\-f <apache config file> \fR
.RS 4
The apache config file containing the information where the keys are located.
.RE

.PP
\fB\-h\fR
.RS 4
Display a help message.
.RE

.SH INTERNET SOURCES
http://www.privacyidea.org, http://www.linotp.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>
