.\" Manpage for privacyidea-create-userdb
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-CREATE-USERDB  1 "11 Oct 2015" "1.0" "privacyidea-create-userdb man page"
.SH NAME
privacyidea-create-userdb \- creates a sqlite user database.
.SH SYNOPSIS
privacyidea-create-userdb
.SH DESCRIPTION
This creates a sqlite3 database at /etc/privacyidea/users.sqlite. In addition it creates an editable
resolver 'localusers' and a realm 'localsql'. 
You can use this realm in privacyIDEA to create users from with the web UI.

.SH INTERNET SOURCES
http://www.privacyidea.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
privacyIDEA <info@privacyidea.org>
