.\" Manpage for privacyidea-create-auditkeys.
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-CREATE-AUDITKEYS 1 "08 May 2014" "1.0" "privacyidea-create-audit man page"
.SH NAME
privacyidea-create-auditkeys \- create the audit signing keys.
.SH SYNOPSIS
privacyidea-create-auditkeys -f <ini file>
.SH DESCRIPTION
This tool creates the audit signing keys for privacyIDEA. It reads the configuration from the privacyidea.ini file
to determine, where the siging keys  should be generated.
.SH COMMON OPTIONS
.PP
\fB\-f <ini file> \fR
.RS 4
The privacyidea.ini file containing the information where the signing keys are located.
.RE

.PP
\fB\-h\fR
.RS 4
Display a help message.
.RE

.SH INTERNET SOURCES
http://www.privacyidea.org, http://www.linotp.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>
