.\" Manpage for privacyidea-fix-access-rights.
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-FIX-ACCESS-RIGHTS 1 "11 Oct 2015" "1.0" "privacyidea-fix-access-rights man page"
.SH NAME
privacyidea-fix-access-rights \- fix the access rights of several files.
.SH SYNOPSIS
privacyidea-fix-access-rights \-f <cfg file> \-u <privacyidea user>
.SH DESCRIPTION
This tool fixes the access rights of the 
 - encryption key
 - log directory
 - pi.cfg file

It reads the locations from the privacyidea.ini file.
.SH COMMON OPTIONS
.PP
\fB\-f <cfg file> \fR
.RS 4
The pi.cfg file containing all necessary information.
.RE

.PP
\fB\-u <privacyidea user> \fR
.RS 4
This is the user, privacyIDEA runs with. Usually "privacyidea".
.RE


.PP
\fB\-h\fR
.RS 4
Display a help message.
.RE

.SH INTERNET SOURCES
http://www.privacyidea.org,  http://www.linotp.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>, privacyIDEA <info@privacyidea.org>
