.\" Manpage for privacyidea-convert-token.
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-CONVERT-TOKEN 1 "11 Oct 2015" "1.0" "convert-token man page"
.SH NAME
privacyidea-convert-token \- converts the Safeword Alpine import data to the Aladdin XML file format.
.SH SYNOPSIS
privacyidea-convert-token \-f <input file> [\-d]
.SH DESCRIPTION
This tool converts the Safeword Alpine import data to the Aladdin XML file format.
.SH COMMON OPTIONS
.PP
\fB\-f <input file> \fR
.RS 4
Here you specify the Safeword data token file that should be converted
.RE

.PP
\fB\-h\fR
.RS 4
Display a helpd message.
.RE

.PP
\fB\-d\fR
.RS 4
Dump the data that is read from the Safeword data file. Do not output the XML file.
.RE

.SH INTERNET SOURCES
http://www.privacyidea.org, http://www.linotp.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>
