.\" Manpage for privacyidea-pip-update.
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-PIP-UPDATE 1 "11 Oct 2015" "1.0" "privacyidea-pip-update man page"
.SH NAME
privacyidea-pip-update \- updates a pip installation, e.g. in a virtualenv.
.SH SYNOPSIS
privacyidea-pip-update [\-f] [\-s] [\-n]
.SH DESCRIPTION
This tool upgrades privacyIDEA and its dependencies via pip and then upgrades
the database schema with privacyidea\-schema\-upgrade.
.SH COMMON OPTIONS
.PP
\fB\-f, \-\-force \fR
.RS 4
Do not ask for confirmation.
.RE

.PP
\fB\-s, \-\-skipstamp \fR
.RS 4
Do not stamp a database that has no version stamp yet.
.RE

.PP
\fB\-n, \-\-noschema \fR
.RS 4
Do not upgrade the database schema.
.RE

.PP
\fB\-h, \-\-help\fR
.RS 4
Display a help message.
.RE

.SH INTERNET SOURCES
http://www.privacyidea.org,  http://www.linotp.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>
