.\" Manpage for privacyidea-pam-remain.
.\" Contact info@privacyidea.org for any feedback.
.TH PRIVACYIDEA-PAM-REMAIN 1 "11 Oct 2015" "1.0" "privacyidea-pam-remain man page"
.SH NAME
privacyidea-pam-remain \- display the remaining offline OTP values for all tokens.
.SH SYNOPSIS
privacyidea-pam-remain
.SH DESCRIPTION
This tool is used to display the remaining OTP values in the local sqlite database
for all local tokens for offline authentication.
It prints a list of the serial number and the number of remaining OTP values.

.SH INTERNET SOURCES
http://www.privacyidea.org,  http://www.linotp.org
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
privacyIDEA <info@privacyidea.org>
