name: Trigger GitLab on Push to master

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  trigger-gitlab:
    name: Trigger internal GitLab pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab pipeline
        env:
          GITLAB_TRIGGER_URL: https://lucan.netknights.it/api/v4/projects/6/trigger/pipeline
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          GITHUB_BRANCH: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPO_URL: git@github.com:${{ github.repository }}.git
        run: |
          curl --fail --request POST "$GITLAB_TRIGGER_URL" \
            --form token="$GITLAB_TRIGGER_TOKEN" \
            --form ref=main \
            --form variables[GITHUB_BRANCH]="$GITHUB_BRANCH" \
            --form variables[GITHUB_SHA]="$GITHUB_SHA" \
            --form variables[GITHUB_REPO]="$GITHUB_REPO_URL"
